import type { Column } from '@/types'
import type { ColumnConfig } from '@/types/column-styles'

export const COLUMNS_MAP: Record<
  string,
  Omit<Column, 'boardSettingsId' | 'id' | 'index' | 'createdAt' | 'updatedAt'>
> = {
  GOOD: {
    columnType: 'GOOD',
    label: 'Went Well',
    tagline: 'What went well?',
    placeholder: 'We had plenty of muffins!',
    emoji: '😊',
    lightBg: '#f0fdf4',
    lightBorder: '#bbf7d0',
    lightTitleBg: '#dcfce7',
    lightTitleText: '#15803d',
    darkBg: '#052e16',
    darkBorder: '#166534',
    darkTitleBg: '#14532d',
    darkTitleText: '#86efac',
  },
  MEH: {
    columnType: 'MEH',
    label: 'Could Be Better',
    tagline: 'What could be better?',
    placeholder: 'The muffins were a little stale.',
    emoji: '😐',
    lightBg: '#fefce8',
    lightBorder: '#fde68a',
    lightTitleBg: '#fef9c3',
    lightTitleText: '#a16207',
    darkBg: '#1c1400',
    darkBorder: '#854d0e',
    darkTitleBg: '#422006',
    darkTitleText: '#fde68a',
  },
  BAD: {
    columnType: 'BAD',
    label: 'Frustrating',
    tagline: 'What was frustrating?',
    placeholder: 'All the muffins were gone...',
    emoji: '😞',
    lightBg: '#fef2f2',
    lightBorder: '#fecaca',
    lightTitleBg: '#fee2e2',
    lightTitleText: '#b91c1c',
    darkBg: '#1c0a0a',
    darkBorder: '#991b1b',
    darkTitleBg: '#450a0a',
    darkTitleText: '#fca5a5',
  },
  SHOUTOUT: {
    columnType: 'SHOUTOUT',
    label: 'Shoutout',
    tagline: 'What are we celebrating?',
    placeholder: 'Felderwin came through with the muffins!',
    emoji: '🎉',
    lightBg: '#eff6ff',
    lightBorder: '#bfdbfe',
    lightTitleBg: '#dbeafe',
    lightTitleText: '#1d4ed8',
    darkBg: '#030b1f',
    darkBorder: '#1e40af',
    darkTitleBg: '#172554',
    darkTitleText: '#93c5fd',
  },
}

export const PRESET_COLUMNS: Record<string, ColumnConfig> = {
  GOOD: {
    label: 'Went Well',
    tagline: 'What went well?',
    placeholder: 'We had plenty of muffins!',
    emoji: '😊',
    light: {
      bg: '#f0fdf4',
      border: '#bbf7d0',
      titleBg: '#dcfce7',
      titleText: '#15803d',
    },
    dark: {
      bg: '#052e16',
      border: '#166534',
      titleBg: '#14532d',
      titleText: '#86efac',
    },
  },
  MEH: {
    label: 'Could Be Better',
    tagline: 'What could be better?',
    placeholder: 'The muffins were a little stale.',
    emoji: '😐',
    light: {
      bg: '#fefce8',
      border: '#fde68a',
      titleBg: '#fef9c3',
      titleText: '#a16207',
    },
    dark: {
      bg: '#1c1400',
      border: '#854d0e',
      titleBg: '#422006',
      titleText: '#fde68a',
    },
  },
  BAD: {
    label: 'Frustrating',
    tagline: 'What was frustrating?',
    placeholder: 'All the muffins were gone...',
    emoji: '😞',
    light: {
      bg: '#fef2f2',
      border: '#fecaca',
      titleBg: '#fee2e2',
      titleText: '#b91c1c',
    },
    dark: {
      bg: '#1c0a0a',
      border: '#991b1b',
      titleBg: '#450a0a',
      titleText: '#fca5a5',
    },
  },
  SHOUTOUT: {
    label: 'Shoutout',
    tagline: 'What are we celebrating?',
    placeholder: 'Felderwin came through with the muffins!',
    emoji: '🎉',
    light: {
      bg: '#eff6ff',
      border: '#bfdbfe',
      titleBg: '#dbeafe',
      titleText: '#1d4ed8',
    },
    dark: {
      bg: '#030b1f',
      border: '#1e40af',
      titleBg: '#172554',
      titleText: '#93c5fd',
    },
  },
}
