export const mockData = [
  {
    id: '1',
    canEdit: true,
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean non dolor ac tellus finibus bibendum. Ut egestas ipsum dui, et tincidunt turpis cursus in. Curabitur, massa id cursus iaculis, nisi libero pulvinar dolor, eget feugiat neque nulla id mi.',
    upvotes: 5,
    isUpvoted: false,
    creatorName: 'Alice',
    isDiscussed: false,
    createdAt: new Date('2025-11-10T18:26:09.019+00:00'),
  },
  {
    id: '2',
    canEdit: false,
    content: 'Need to improve communication during standups.',
    upvotes: 8,
    isUpvoted: true,
    creatorName: 'Bob',
    isDiscussed: true,
    createdAt: new Date('2025-11-10T18:26:02.019+00:00'),
  },
  {
    id: '3',
    canEdit: true,
    content: 'Code reviews have been faster this sprint!',
    upvotes: 3,
    isUpvoted: false,
    creatorName: 'Alice',
    isDiscussed: false,
    createdAt: new Date('2025-11-10T18:26:45.019+00:00'),
  },
  {
    id: '4',
    canEdit: false,
    content: 'Let’s celebrate the reduced deployment time!',
    upvotes: 12,
    isUpvoted: true,
    creatorName: 'Derek',
    isDiscussed: true,
    createdAt: new Date('2025-11-10T18:26:25.019+00:00'),
  },
  {
    id: '5',
    canEdit: false,
    content: 'Design handoff process felt smoother this week.',
    upvotes: 6,
    isUpvoted: false,
    creatorName: 'Ella',
    isDiscussed: false,
    createdAt: new Date('2025-11-10T18:36:15.019+00:00'),
  },
  {
    id: '6',
    canEdit: false,
    content: 'QA caught fewer issues this cycle — need to review coverage.',
    upvotes: 4,
    isUpvoted: false,
    creatorName: 'Frank',
    isDiscussed: true,
    createdAt: new Date('2025-11-10T18:26:09.019+00:00'),
  },
  {
    id: '7',
    canEdit: true,
    content: 'New CI/CD workflow saved us hours!',
    upvotes: 10,
    isUpvoted: true,
    creatorName: 'Alice',
    isDiscussed: false,
    createdAt: new Date('2025-11-10T18:26:59.019+00:00'),
  },
  {
    id: '8',
    canEdit: false,
    content: 'Team morale was high — great collaboration overall.',
    upvotes: 7,
    isUpvoted: false,
    creatorName: 'Hannah',
    isDiscussed: false,
    createdAt: new Date('2025-11-10T18:26:48.019+00:00'),
  },
  {
    id: '9',
    canEdit: false,
    content: 'We need clearer acceptance criteria in stories.',
    upvotes: 9,
    isUpvoted: true,
    creatorName: 'Ian',
    isDiscussed: true,
    createdAt: new Date('2025-11-10T18:27:48.019+00:00'),
  },
  {
    id: '10',
    canEdit: true,
    content: 'Sprint planning felt a bit rushed — need better prep time.',
    upvotes: 2,
    isUpvoted: false,
    creatorName: 'Alice',
    isDiscussed: false,
    createdAt: new Date('2025-11-10T18:25:09.019+00:00'),
  },
]
