export type RetroBoardActionType = {
  SET_FROM_BOARD: 'SET_FROM_BOARD'
  ADD_CARD: 'ADD_CARD'
  UPDATE_CARD: 'UPDATE_CARD'
  DELETE_CARD: 'DELETE_CARD'
  TOGGLE_UPVOTE: 'TOGGLE_UPVOTE'
  MARK_DISCUSSED: 'MARK_DISCUSSED'
  ADD_ACTION_ITEM: 'ADD_ACTION_ITEM'
  TOGGLE_DONE_ACTION_ITEM: 'TOGGLE_DONE_ACTION_ITEM'
  UPDATE_ACTION_ITEM: 'UPDATE_ACTION_ITEM'
}
