import { VotingMode } from '@/enums'
import type { BoardSettingsWithPermissionsNoIcons } from './types'

export const BASE_SETTINGS: BoardSettingsWithPermissionsNoIcons = {
  private: {
    render: false,
    canEdit: false,
    enabled: false,
    hint: 'Only board owners can change privacy settings',
    isUnlocked: true,
    key: 'isPrivate',
    title: 'Private Board',
    subsettings: {
      openAccess: {
        canEdit: false,
        enabled: false,
        key: 'privateOpenAccess',
        kind: 'toggle',
        title: 'Enable Guest Access',
      },
      cardRetention: {
        canEdit: false,
        key: 'privateCardRetention',
        kind: 'value',
        title: 'Card Retention (Discussed)',
        value: 7,
      },
    },
  },
  comments: {
    render: false,
    canEdit: false,
    enabled: false,
    isUnlocked: true,
    key: 'isCommentsEnabled',
    title: 'Comments',
    subsettings: {
      anytime: {
        canEdit: false,
        enabled: false,
        key: 'commentsAnytime',
        kind: 'toggle',
        title: 'Allow Comments Anytime',
      },
      restricted: {
        canEdit: false,
        enabled: false,
        key: 'commentsRestricted',
        kind: 'toggle',
        title: 'Only Members And Above Can Comment',
      },
    },
  },
  music: {
    render: true,
    canEdit: false,
    enabled: false,
    isUnlocked: true,
    key: 'isMusicEnabled',
    title: 'Music',
    subsettings: {
      anytime: {
        canEdit: false,
        enabled: false,
        key: 'musicAnytime',
        kind: 'toggle',
        title: 'Allow Music Anytime',
      },
      restricted: {
        canEdit: false,
        enabled: false,
        key: 'musicRestricted',
        kind: 'toggle',
        title: 'Only Facilitators And Above Have Control',
      },
    },
  },
  timer: {
    render: true,
    canEdit: false,
    enabled: false,
    isUnlocked: true,
    key: 'isTimerEnabled',
    title: 'Timer',
    subsettings: {
      restricted: {
        canEdit: false,
        enabled: false,
        key: 'timerRestricted',
        kind: 'toggle',
        title: 'Only Facilitators And Above Have Control',
      },
      defaultDuration: {
        canEdit: false,
        key: 'timerDefault',
        kind: 'value',
        title: 'Default Timer Duration (seconds)',
        value: 300,
      },
    },
  },
  actionItems: {
    render: true,
    canEdit: false,
    enabled: false,
    isUnlocked: true,
    key: 'isActionItemsEnabled',
    title: 'Action Items',
    subsettings: {
      anytime: {
        canEdit: false,
        enabled: false,
        key: 'actionItemsAnytime',
        kind: 'toggle',
        title: 'Allow Action Items Anytime',
      },
      restricted: {
        canEdit: false,
        enabled: false,
        key: 'actionItemsRestricted',
        kind: 'toggle',
        title: 'Only Facilitators And Above Can Manage',
      },
    },
  },
  upvoting: {
    render: true,
    canEdit: false,
    enabled: false,
    isUnlocked: true,
    key: 'isUpvotingEnabled',
    title: 'Upvoting',
    subsettings: {
      anytime: {
        canEdit: false,
        enabled: false,
        key: 'upvoteAnytime',
        kind: 'toggle',
        title: 'Allow Upvoting Anytime',
      },
      limit: {
        canEdit: false,
        hint: '-1 for unlimited',
        key: 'upvoteLimit',
        kind: 'value',
        title: 'Upvote Limit',
        value: -1,
      },
      restricted: {
        canEdit: false,
        enabled: false,
        key: 'upvoteRestricted',
        kind: 'toggle',
        title: 'Only Members And Above Can Upvote',
      },
    },
  },
  voting: {
    render: true,
    canEdit: false,
    enabled: false,
    isUnlocked: true,
    key: 'isVotingEnabled',
    title: 'Voting',
    subsettings: {
      votingMode: {
        canEdit: false,
        key: 'votingMode',
        kind: 'choice',
        title: 'Mode',
        choices: [],
        choice: VotingMode.MULTI,
      },
      limit: {
        canEdit: false,
        hint: '-1 for unlimited',
        key: 'votingLimit',
        kind: 'value',
        title: 'Voting Limit',
        value: -1,
      },
      restricted: {
        canEdit: false,
        enabled: false,
        key: 'votingRestricted',
        kind: 'toggle',
        title: 'Only Members and Above Can Vote',
      },
    },
  },
}
