export enum BoardSettingsMessageType {
  UPDATE_BOARD_SETTINGS = 'UPDATE_BOARD_SETTINGS',
  // UPDATE_PERMISSIONS = 'UPDATE_PERMISSIONS',
  CREATE_INVITATION_LINK = 'CREATE_INVITATION_LINK',
  REVOKE_INVITATION_LINK = 'REVOKE_INVITATION_LINK',
  NEW_MEMBER_ADDED = 'NEW_MEMBER_ADDED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  UPDATE_MEMBER_ROLE = 'UPDATE_MEMBER_ROLE',
}

export enum BoardSettingsInternalActionType {
  OPEN_SIDEBAR = 'OPEN_SIDEBAR',
  CLOSE_SIDEBAR = 'CLOSE_SIDEBAR',
  UPDATE_PERMISSIONS = 'UPDATE_PERMISSIONS',
}
