export enum BoardCardsMessageType {
  ADD_CARD = 'ADD_CARD',
  UPDATE_CARD = 'UPDATE_CARD',
  DELETE_CARD = 'DELETE_CARD',
  DELETE_ALL_CARDS = 'DELETE_ALL_CARDS',
  DELETE_COMPLETED_CARDS = 'DELETE_COMPLETED_CARDS',
  TOGGLE_UPVOTE = 'TOGGLE_UPVOTE',
  ADD_ACTION_ITEM = 'ADD_ACTION_ITEM',
  UPDATE_ACTION_ITEM = 'UPDATE_ACTION_ITEM',
  DELETE_ACTION_ITEM = 'DELETE_ACTION_ITEM',
  ADD_CARD_COMMENT = 'ADD_CARD_COMMENT',
  UPDATE_CARD_COMMENT = 'UPDATE_CARD_COMMENT',
  DELETE_CARD_COMMENT = 'DELETE_CARD_COMMENT',
  SORT_CARDS = 'SORT_CARDS',
}

export enum BoardCardsInternalActionType {
  FILTER_CARDS = 'FILTER_CARDS',
  CLOSE_VOTING_RESULTS = 'CLOSE_VOTING_RESULTS',
  RESET_VOTING_RESULTS = 'RESET_VOTING_RESULTS',
  RESYNC_CARDS = 'RESYNC_CARDS',
}

export enum BoardCardsSortOptions {
  BY_VOTES = 'BY_VOTES',
  BY_UPVOTES = 'BY_UPVOTES',
  BY_DISCUSSED = 'BY_DISCUSSED',
  BY_ACTION_ITEM_COUNT = 'BY_ACTION_ITEM_COUNT',
  BY_COMMENT_COUNT = 'BY_COMMENT_COUNT',
  BY_NEWEST = 'BY_NEWEST',
  BY_OLDEST = 'BY_OLDEST',
  NONE = 'NONE',
}

export enum BoardCardsFilterOptions {
  ALL = 'ALL',
  WITH_VOTES = 'WITH_VOTES',
  WITHOUT_VOTES = 'WITHOUT_VOTES',
}
